# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

# Build docs in all formats (html, pdf, epub)
formats: all

# Set the version of Python and requirements required to build the docs
build:
   os: ubuntu-22.04
   tools:
      python: "3.11"
   jobs:
      pre_install:
         - grep -v "python-ldap" requirements-docs.txt > tempreqs && mv tempreqs requirements-docs.txt


python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs
