---
version: '2.0'
services:
  test:
    build: .
    volumes:
      - ".:/app"
    links:
      - postgres
    command: make test
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://lemur:lemur@postgres:5432/lemur
      VIRTUAL_ENV: 'true'

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_USER: lemur
      POSTGRES_PASSWORD: lemur

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
