"""Adds the endpoint_dnsalias table to store CloudFront distribution aliases.

Revision ID: 189e5fda5bf8
Revises: 2201c548a5a1
Create Date: 2021-10-25 19:52:44.133743

"""

# revision identifiers, used by Alembic.
revision = "189e5fda5bf8"
down_revision = "2201c548a5a1"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint_dnsalias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=True),
        sa.Column("alias", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("endpoint_dnsalias")
    # ### end Alembic commands ###
