"""empty message

Revision ID: 434c29e40511
Revises: 8323a5ea723a
Create Date: 2020-09-11 17:24:51.344585

"""

# revision identifiers, used by Alembic.
revision = "434c29e40511"
down_revision = "8323a5ea723a"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "certificates", sa.Column("key_type", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("certificates", "key_type")
    # ### end Alembic commands ###
