"""Adding logging database tables.

Revision ID: e3691fc396e9
Revises: 932525b82f1a
Create Date: 2016-11-28 13:15:46.995219

"""

# revision identifiers, used by Alembic.
revision = "e3691fc396e9"
down_revision = "932525b82f1a"

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("certificate_id", sa.Integer(), nullable=True),
        sa.Column("log_type", sa.Enum("key_view", name="log_type"), nullable=False),
        sa.Column(
            "logged_at",
            sqlalchemy_utils.types.arrow.ArrowType(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["certificate_id"], ["certificates.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    ### end Alembic commands ###
